### ISSUE TITLE
Change of default gateway doesn't work

### ISSUE THREAD

**Issue by yvesf** [yvesf/andiodine#1]
reported by _s4dsniper_ (Thanks!)

It seems you don't change the default gateway after DNS tunnel is ready so,
the only thing you can reach is the iodine server (via IP). If I launch my
browser and try to reach a website : nothing load.

But if you do (in Terminad Emulator):

```
# busybox route del default
# busybox route add default gw 172.16.0.1 (iodine server IP)
```

web is working, even if very slow (as expected)

So maybe I'm missing something but shouldn't AndIodine change the default
gateway to route all traffic in the DNS tunnel ?

**Comment by alanbazan0** [comment]
Does someone have Maggic tunnel for android 5.0? andiodine connects but i can't open any page with the browser. i need help

**Comment by mcastillof** [comment]
Routing is working for me, and I can browse the web without problem (just a bit slow). 

Remember to allow IP forwarding in your kernel with:
# echo 1 > /proc/sys/net/ipv4/ip_forward

And configure iptables to forward the packets:
# iptables -A FORWARD -i dns0 -o eth0 -j ACCEPT
# iptables -A FORWARD -i eth0 -o dns0 -m state --state RELATED,ESTABLISHED  -j ACCEPT 
# iptables -t nat -A POSTROUTING  -o eth0 -j MASQUERADE

**Comment by yvesf** [comment]
unfortunately nothing can do about the speed :) Thanks for this feedback.

Just to be clear: @mcastillof is talking about the server-side in the comment above.

**Comment by segganeadel** [comment]
Same here can ping and ssh to server but no internet 
Tried to change route same thing no Internet

Actually I'm curious how slowdns and your-freedom do it

**Comment by yvesf** [comment]
@segganeadel things you could try:
- check if it works from a linux machine with standard iodine
- `adb shell` on the phone to see if the routing wasn't set up properly (wrong/no default gateway)
- record the output of `adb logcat` of the connection process, put it in a [gist](https://gist.github.com) and share it.
- tcpdump on the iodine interface on the server side to see if pings to an external address are arriving at the iodine server

I'm not sure what you mean by your last sentence. If you're asking about how the speed of the working tunnel will be: yes it will be quite slow.

**Comment by angrierhorse** [comment]
About 3 years and many android devices later I have revisited this.

It has finally dawned on me that the majority of the routing issues faced by users are due to NAT not being set-up on the server.  Most of the online guides for getting a working iodine setup working omit this step.

See: http://ip-dns.info/

Specifically the last part about setting up NAT and IP masq.

Again, if your setup has the default route set correctly on the client and you can ping the server however no traffic appears to be getting through, make sure you have configured NAT and IP masq correctly on your server.

**Comment by yvesf** [comment]
I'm closing this as it's quiet old and the more or less solved. Thanks for all the contributions to this discussion.
