### ISSUE TITLE
Setting "Request Type" does not seem to take effect

### ISSUE THREAD

**Issue by Orbixx** [yvesf/andiodine#18]
I have set Request Type to something other than AUTODETECT, but it still attempts to autodetect. Is this field being used when connecting?

**Comment by 2m** [comment]
After a quick look at the code it seems that it is not used when [calling](https://github.com/yvesf/andiodine/blob/899ec173be1151ac603744d5b39cd2746f66be38/src/main/java/org/xapek/andiodine/IodineClient.java#L11-L12) `iodine` native code.

**Comment by Orbixx** [comment]
Not sure if I'm going crazy, but I think it tried to use a specific record type that I selected, but it wasn't the one I had set at the time.

I also see what you mean about it not being called, so perhaps I am indeed just going crazy.

**Comment by 2m** [comment]
Looking more at the code it seems that it is always autodetecting request type irregardless of the selected request type.

**Comment by yvesf** [comment]
I can confirm that. Looks like I forgot about that aspect after modeling the Configuration.
Basically it's just a matter of converting the Java-Enum to string and adding  to `Java_org_xapek_andiodine_IodineClient_connect` and calling  `client_set_qtype("A")` with it.
