### ISSUE TITLE
What iodine version is being used?

### ISSUE THREAD

**Issue by parkerlreed** [yvesf/andiodine#22]
I have everything setup but it seems like it fails the version check. I'm using 0.7.0 on my computer.

**Comment by yvesf** [comment]
andiodine uses iodine 0.7.0. Please provide more information such as:
- the andiodine version
- invocation of server, andiodine configuration
- debug output (logcat for andiodine, stdout of server. Mask your IPs/Passwords!)

**Comment by parkerlreed** [comment]
I don't have the device I was testing on anymore. My server launch line is 
````
sudo iodined -c -f 10.0.0.1 -P somepassword tunnel.yourwebsite.party
````

And the line I use to connect
````
sudo ./iodine -f -P somepassword tunnel.yourwebsite.party
````

I think I just got jumbled up on what went where in andiodine.
