### ISSUE TITLE
How fast should iodine be?

### ISSUE THREAD

**Issue by SudoHenk** [yvesf/andiodine#23]
Hi,

I have iodine running on a 100MB/s server, and just tried it on my mobile phone (with andiodine, worked fine at once), but loading websites is slow, very slow.

Simple HTTP request (eg. http://api.ipify.org/?format=json) takes me 1 second. A website like reddit.com (HTTPS) takes well over 50 seconds to load.

Is this just a side effect of the conversion to DNS (being so inefficient), or is something else happening?

**Comment by SudoHenk** [comment]
I followed https://github.com/yarrick/iodine (all default parameters) and have a ping of 20ms.

**Comment by SudoHenk** [comment]
@yvesf any take on this?

**Comment by yvesf** [comment]
performance depend mainly on the specific network setup, means the dns relays involved.

I recommended you play a bit with iodine on a computer to find the best setup and just try to make the same settings in andione. Most commandline switches are already exposed in some way. Feel free to share you experience here.

If downstream is lower than upstream then most likely something is very wrong.
The actual network-bandwidth of the server doesn't make a big difference.
Obviously the performance will never be near native. Even in "raw mode" the overhead is huge.
