### ISSUE TITLE
Not working on Android 6.x?

### ISSUE THREAD

**Issue by hackrid** [yvesf/andiodine#26]
Hi
I have trouble getting the app running on Android  6.x
Is this known already?

**Comment by faxm0dem** [comment]
WFM on a Honor 7

**Comment by yvesf** [comment]
Thank you both for your feedback.
@hackrid could you post a stacktrace if you think it could help to identify the problem (as always, don't forget to mask your private data in the stacktrace :smiley:)

**Comment by hackrid** [comment]
There is no error message displayed, andiodine just closes without any notice once I try to activate the connection

**Comment by yvesf** [comment]
To get a detailed error trace you have to use [logcat](https://developer.android.com/studio/command-line/logcat.html). If you have no experience with you may find it complicated.
Please be aware that I cannot give you something like customer-support in this issue-tracker. That means you may have to wait for somebody who runs into the same problem and knows how to identify and fix it.

**Comment by yvesf** [comment]
I've justed tested on Android 6. So I'll close this.
