### ISSUE TITLE
VPN not working

### ISSUE THREAD

**Issue by nico202** [yvesf/andiodine#41]
Hi, I'm on android 7.1.2, f-droid andiodine build (1.3).

Connecting to the tunnel does work. After the packet size negitiation, I can use a terminal emulator and connect to my server (10.0.0.1) through the tunnel. However. even if android tells me that I'm connected to a VPN, no app can access the internet through it.

I don't know if this is known or how to debug it (i can run a logcat if needed)

**Comment by nico202** [comment]
(PS: thanks, ssh-ing to my server without a real internet connection already saved my life :) )

**Comment by faxm0dem** [comment]
Did you set up ip forwarding on your server running iodined?

**Comment by angrierhorse** [comment]
About 9/10 the reason you can connect to your server but not reach the wider net is because you have not properly configured IP forwarding on you iodine server.

**Comment by nico202** [comment]
Yeah I think this is the problem, still I don't know how to fix it. I'm using:
```sysctl -w net.ipv4.ip_forward=1```

**Comment by yvesf** [comment]
I'm closing this as it seems that it was related to network setup rather than the android app.

**Comment by amenk** [comment]
@nico202 where you able to solve it? also tried ip_forward=1 -> not working
