### ISSUE TITLE
andiodine + openvpn tunnel?

### ISSUE THREAD

**Issue by gr01d** [yvesf/andiodine#42]
I read somewhere that Iodine is not secure (dns?) and you need to route it to another tunnel like OPenVPN how can I achieve this using the android app?
BTW, On android 7.1.2 the program crashes after randomly.

**Comment by yvesf** [comment]
For the crashes please open another issue with logcat output including the stacktrace (mask private information therein).

It is true that dns-tunnels such as it is implemented in iodine is not a secure channel. I doesn't replace openvpn.

I'm not aware that it's possible to have one tunnel in another tunnel using Android, please correct me if I'm wrong.
