### ISSUE TITLE
v1.4 should be on F-droid

### ISSUE THREAD

**Issue by doronbehar** [yvesf/andiodine#43]
The F-droid version of AndIodine is outdated - https://f-droid.org/en/packages/org.xapek.andiodine/

**Comment by yvesf** [comment]
this issue needs to be raised in fdroid-data https://gitlab.com/fdroid/fdroiddata/issues

**Comment by doronbehar** [comment]
I've reported it there: https://gitlab.com/fdroid/fdroiddata/issues/1161

And here is quoted respond:
> Can't update to this version because the version code didn't change upstream, it's still marked as version 1.3/3: https://github.com/yvesf/andiodine/blob/v1.4/src/main/AndroidManifest.xml#L4-L5
> Can you report this problem upstream?

**Comment by yvesf** [comment]
Please use v1.5 which also has the proper version in `AndroidManifest.xml`
