### ISSUE TITLE
andiodine 1.5 build

### ISSUE THREAD

**Issue by angrierhorse** [yvesf/andiodine#45]
Will there be an apk release of version 1.5?  I appreciate you may have limited time but I have to ask.

**Comment by yvesf** [comment]
I would prefer it that APK is build and distributed by f-droid (they have APK downloads on their website).

There is an open issue: https://gitlab.com/fdroid/fdroiddata/issues/1161

I'll ask if they could update to 1.5 (since I've now implemented the changes they suggested)

**Comment by yvesf** [comment]
Andiodine 1.6 is now in f-droid

**Comment by angrierhorse** [comment]
Thank you yvesf.  Your work is greatly appreciated.
